---
- name: Ensure pip3 is installed
  apt:
    name: python3-pip  # This will install pip3
    state: present

- name: Install Python 3 MySQL client libraries
  apt:
    name:
      - python3-pymysql  # PyMySQL client for Python 3
      - python3-dev      # Required for compiling some libraries (like mysqlclient)
      - libmysqlclient-dev # MySQL client libraries for development
    state: present

- name: Install MySQL client library for Python3 (using apt)
  apt:
    name: python3-mysqldb
    state: present

- name: Set Python interpreter for Ansible
  set_fact:
    ansible_python_interpreter: /usr/bin/python3

- name: Install MariaDB
  apt:
    name: mariadb-server
    state: present

- name: Ensure MariaDB is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create Angular app database
  mysql_db:
    name: "{{ mariadb_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    owner: root
    group: root
    mode: "0644"

- name: Create MariaDB user for Angular app
  mysql_user:
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_password }}"
    priv: "{{ mariadb_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    owner: root
    group: root
    mode: "0644"

- name: Generate seed data SQL file
  template:
    src: seed_data.sql.j2
    dest: /tmp/seed_data.sql
    owner: root
    group: root
    mode: "0644"

- name: Import seed data into MariaDB
  mysql_db:
    name: "{{ mariadb_db_name }}"
    state: import
    target: "/tmp/seed_data.sql"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    owner: root
    group: root
    mode: "0644"
...