---
- name: Install MariaDB
  apt:
    name: mariadb-server
    state: present

- name: Ensure MariaDB is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create Angular app database
  mysql_db:
    name: "{{ mariadb_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Create MariaDB user for Angular app
  mysql_user:
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_password }}"
    priv: "{{ mariadb_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Generate seed data SQL file
  template:
    src: seed_data.sql.j2
    dest: /tmp/seed_data.sql
    owner: root
    group: root
    mode: "0644"
    
- name: Import seed data into MariaDB
  mysql_db:
    name: "{{ mariadb_db_name }}"
    state: import
    target: "/tmp/seed_data.sql"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
...