---
- name: Install Node.js
  apt:
    name: nodejs
    state: present
  become: true

- name: Install npm (Node.js package manager)
  apt:
    name: npm
    state: present
  become: true

- name: Install MySQL Node.js module
  npm:
    name: mysql
    state: present
    global: yes
  become: true

- name: Create app-database in MariaDB
  mysql_db:
    name: app-database
    state: present
    login_user: root
    login_password: "{{ api_db_password }}"
  become: true

- name: Create MariaDB user for app-database
  mysql_user:
    name: "{{ api_db_user }}"
    password: "{{ api_db_password }}" 
    priv: "{{ api_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ api_db_root_password }}"

- name: Create API data table in app-database (optional)
  mysql_query:
    query: |
      CREATE TABLE IF NOT EXISTS api_data (
         id INT AUTO_INCREMENT PRIMARY KEY,
         name VARCHAR(255) NOT NULL,
         description TEXT
      );
    login_user: root
    login_password: "{{ api_db_password }}"
    login_db: app-database
  become: true

- name: Create directory for the API server
  file:
    path: "/opt/api-server"
    state: directory
  become: true

- name: Deploy API server code
  copy:
    src: api-server/files/api-server.js
    dest: "/opt/api-server/api-server.js"
    mode: '0644'
  become: true

- name: Configure API server to connect to MariaDB
  copy:
    src: api-server/files/api-server.config.js
    dest: "/opt/api-server/api-server.config.js"
    mode: '0644'
  become: true

- name: Create systemd service for the API server
  template:
    src: api-server/templates/api-server.service.j2
    dest: "/etc/systemd/system/api-server.service"
  become: true

- name: Start and enable the API server service
  service:
    name: api-server
    state: started
    enabled: true
  become: true
...