---
- name: Create the deployment directory for the version
  file:
    path: "/var/www/html/{{ VERSION }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copy the Angular app artifact to the remote server
  copy:
    src: "/tmp/angular-devops-app-artifact-{{ VERSION }}.tar.gz"
    dest: "/home/ubuntu/angular-devops-app-artifact-{{ VERSION }}.tar.gz"
    mode: '0644'
  when: build_output.stat.exists  # Ensure that the artifact exists on Jenkins agent

- name: extract the angular app artifact from the remote server
  unarchive:
    src: "/home/ubuntu/angular-devops-app/angular-devops-app-artifact-{{ VERSION }}.tar.gz"
    dest: "/var/www/html/{{ VERSION }}"
    remote_src: yes

- name: Remove the old symlink (if it exists)
  file:
    path: "/var/www/html/current"
    state: absent
  ignore_errors: yes

- name: Set up symlink to the latest version
  file:
    src: "/var/www/html/{{ VERSION }}"
    dest: "/var/www/html/current"
    state: link

- name: Clean up the artifact after deployment
  file:
    path: "/home/ubuntu/angular-devops-app-artifact-{{ VERSION }}.tar.gz"
    state: absent
  when: build_output.stat.exists  # Only remove if artifact exists
...