---
- name: Create the deployment directory for the version
  file:
    path: "/var/www/html/{{ VERSION }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: extract the angular app artifact from the remote server
  unarchive:
    src: "/home/ubuntu/angular-devops-app/angular-devops-app-artifact-{{ VERSION }}.tar.gz"
    dest: "/var/www/html/{{ VERSION }}"
    remote_src: yes

- name: Remove the old symlink (if it exists)
  file:
    path: "/var/www/html/current"
    state: absent
  ignore_errors: yes

- name: Set up symlink to the latest version
  file:
    src: "/var/www/html/{{ VERSION }}"
    dest: "/var/www/html/current"
    state: link
...