- name: Create the deployment directory for the version
  file:
    path: "/var/www/html/{{ artifact_version }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Extract the Angular app artifact
  unarchive:
    src: "/tmp/{{ artifact }}"
    dest: "/var/www/html/{{ artifact_version }}"
    remote_src: yes

- name: Set up symlink to the latest version
  file:
    src: "/var/www/html/{{ artifact_version }}"
    dest: "/var/www/html/current"
    state: symlink