---
- name: Create the deployment directory for the version
  file:
    path: "/var/www/html/{{ artifact_version }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: extract the angular app artifact from the remote server
  unarchive:
    src: "/home/ubuntu/angular-devops-app/angular-devops-app-artifact.tar.gz"
    dest: "/var/www/html/{{ artifact_version }}"
    remote_src: yes

- name: Set up symlink to the latest version
  file:
    src: "/var/www/html/{{ artifact_version }}"
    dest: "/var/www/html/current"
    state: symlink
...