---
- name: Install dependencies (Node.js, npm, Angular CLI)
  apt:
    name:
     - nodejs
     - npm
    state: present
    update_cache: yes

- name: Install Angular CLI globally
  npm:
   name: "@angular/cli@16"
   global: yes
   state: present

- name: copy the angular root directory to the nodes
  copy:
    src: angular-devops-app/
    dest: /home/ubuntu/angular-devops-app/
    owner: www-data
    group: www-data
    mode: "0755"

- name: installing angular dependencies
  shell: npm install
  args:
    chdir: /home/ubuntu/angular-devops-app/

- name: Build the Angular project for production
  shell: ng build --configuration production
  args:
    chdir: /home/ubuntu/angular-devops-app/

- name: Check if build output exists
  stat:
    path: /home/ubuntu/angular-devops-app/dist/angular-devops-app
  register: build_output

- name: Fail if build directory does not exist
  fail:
    msg: "The build directory /home/ubuntu/angular-devops-app/dist/angular-devops-app does not exist."
  when: not build_output.stat.exists

- name: Debugging -Show build output directory content
  shell: ls -l /home/ubuntu/angular-devops-app/dist/angular-devops-app/
  when: build_output.stat.exists

- name: Copy built Angular files to Apache document root
  copy:
    src: /home/ubuntu/angular-devops-app/dist/angular-devops-app/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: "0755"
    remote_src: yes

- name: set correct permissions for Apache
  file:
    path: "/var/www/html/"
    owner: www-data
    group: www-data
    recurse: yes
    mode: "0755"
    
- name: Restart Apache
  service:
    name: apache2
    state: restarted
...