---
- name: Install dependencies (Node.js, npm, Angular CLI)
  apt:
    name: 
     - nodejs
     - npm
    state: present
    update_cache: yes
  
- name: Install Angular CLI globally
  npm: 
   name: "@angular/cli@16"
   global: yes
   state: present

- name: copy the angular root directory to the nodes
  copy:
    src: ./angular-devops-app
    dest: /home/ubuntu/angular-devops-app/
    owner: www-data
    group: www-data
    mode: "0755"
    
- name: Build the Angular project for production
  shell: ng build --configuration production
  args:
    chdir: /home/ubuntu/angular-devops-app/


- name: Copy built Angular files to Apache document root
  synchronize:
    src: /home/ubuntu/angular-devops-app/dist/angular-devops-app/
    dest: /var/www/angular-devops-app/
    mode: push
    become: true
...