- name: Install dependencies (Node.js, npm, Angular CLI)
  apt:
    name:
     - nodejs
     - npm
    state: present
    update_cache: yes

- name: Install Angular CLI globally
  npm:
   name: "@angular/cli@16"
   global: yes
   state: present

- name: Copy the angular root directory to the nodes
  copy:
    src: angular-devops-app/
    dest: /home/ubuntu/angular-devops-app/
    owner: www-data
    group: www-data
    mode: "0755"

- name: Installing angular dependencies
  shell: npm install
  args:
    chdir: /home/ubuntu/angular-devops-app/

- name: Build the Angular project for production
  shell: ng build --configuration production
  args:
    chdir: /home/ubuntu/angular-devops-app/

- name: Check if build output exists
  stat:
    path: /home/ubuntu/angular-devops-app/dist/angular-devops-app
  register: build_output

- name: Fail if build directory does not exist
  fail:
    msg: "The build directory /home/ubuntu/angular-devops-app/dist/angular-devops-app does not exist."
  when: not build_output.stat.exists

- name: Debugging - Show build output directory content
  shell: ls -l /home/ubuntu/angular-devops-app/dist/angular-devops-app/
  when: build_output.stat.exists

- name: Debugging VERSION
  debug:
    msg: "The current VERSION is {{ VERSION }}"

- name: Create artifact (tar.gz) of the built Angular project
  command:
    cmd: "tar -czvf /home/ubuntu/angular-devops-app/angular-devops-app-artifact-{{ VERSION }}.tar.gz -C /home/ubuntu/angular-devops-app/dist/ angular-devops-app"
  when: build_output.stat.exists

- name: Set correct permissions for the artifact
  file:
    path: "/home/ubuntu/angular-devops-app/angular-devops-app-artifact-{{ VERSION }}.tar.gz"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Copy built Angular files to Apache document root
  copy:
    src: /home/ubuntu/angular-devops-app/dist/angular-devops-app/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: "0755"
    remote_src: yes

- name: Find all directories under Apache document root
  find:
    paths: "/var/www/html/"
    recurse: yes
    file_type: directory
  register: html_dirs

- name: Set permissions for directories excluding symlinks
  file:
    path: "{{ item.path }}"
    owner: www-data
    group: www-data
    mode: "0755"
  loop: "{{ html_dirs.files }}"
  when: not item.islnk and item.path != '/var/www/html/current'  # Exclude symlinks and 'current' directory

- name: Restart Apache
  service:
    name: apache2
    state: restarted

- name: Fetch the Angular artifact to Jenkins agent
  fetch:
    src: "/home/ubuntu/angular-devops-app/angular-devops-app-artifact-{{ VERSION }}.tar.gz"
    dest: "/tmp/angular-devops-app-artifact-{{ VERSION }}.tar.gz"
    flat: yes
  when: build_output.stat.exists
