---

- name: Ensure the angular project directory exists
  copy:
    src: src/app/package.json
    dest: /var/www/angular-devops-app/package.json
    owner: www-data
    group: www-data
    mode: '0755'

- name: Install dependencies (Node.js, npm, Angular CLI)
  apt:
    name: 
     - nodejs
     - npm
    state: present
    update_cache: yes
  
- name: Install Angular CLI globally
  npm: 
   name: "@angular/cli@16"
   global: yes
   state: present

- name: Build the Angular project for production
  command: ng build --prod
  args:
    chdir: /var/www/angular-devops-app/ 

- name: Copy built Angular files to Apache document root
  synchronize:
    src: /var/www/angular-devops-app/dist/
    dest: /var/www/html/  
    mode: push
    recursive: yes
    owner: www-data
    group: www-data
    mode: '0755'
    become: true
...