---
- name: Install dependencies (Node.js, npm, Angular CLI)
  apt:
    name: 
     - nodejs
     - npm
    state: present
    update_cache: yes
  
- name: Install Angular CLI globally
  npm: 
   name: "@angular/cli@16"
   global: yes
   state: present

- name: clone the angular app repository
  git:
    repo: https://github.com/Abimbola-star/AngularTeam20.git
    dest: /home/ec2-user/AngularTeam20/angular-devops-app
    version: main

- name: Build the Angular project for production
  shell: ng build --configuration production"
  args:
    chdir: /home/ec2-user/AngularTeam20/angular-devops-app


- name: Copy built Angular files to Apache document root
  synchronize:
    src: /home/ec2-user/AngularTeam20/angular-devops-app/dist/angular-devops-app
    dest: /var/www/angular-devops-app/
    mode: push
    become: true
...