---
- name: Ensure the angular project directory exists
  synchronize:
    src: my-angular-app
    dest: /var/www/angular-devops-app
    mode: push
    recursive: yes

- name: Install dependencies (Node.js, npm, Angular CLI)
  apt:
    name: 
     - nodejs
     - npm
    state: present
    update_cache: yes
  
- name: Install Angular CLI globally
  npm: 
   name: "@angular/cli@16"
   global: yes
   state: present

- name: Install project dependencies (npm install)
  command: npm install
  args:
    chdir: /var/www/angular-devops-app/

- name: Build the Angular project for production
  command: ng build --prod
  args:
    chdir: /var/www/angular-devops-app/ 

- name: Set ownership and permissions for the project directory
  file:
    path: /var/www/angular-devops-app/
    owner: www-data
    group: www-data
    mode: '0755'
    recurse: yes

- name: Set ownership and permissions for the dist folder
  file:
    path: /var/www/angular-devops-app/dist/
    owner: www-data
    group: www-data
    mode: '0755'
    recurse: yes


- name: Copy built Angular files to Apache document root
  synchronize:
    src: /var/www/angular-devops-app/dist/
    dest: /var/www/html/  
    mode: push
    recursive: yes
    become: true
...