---
- name: Install dependencies (Node.js, npm, Angular CLI)
  apt:
    name: 
     - nodejs
     - npm
    state: present
    update_cache: yes
    become: true
  
- name: Install Angular.js
  npm: name:@angular/cli@10 global:yes
  state: present

- name: Build the Angular project
  command: ng build --prod
  args: 
    chdir: /var/www/angular-devops-app
  become: true

- name: Copy built angular files to apache directory
  copy:
    src: /var/www/angular-devops-app/dist/
    dest: /var/www/angular-devops-app
    owner: www-data
    group: www-data
    mode: '0755'
  become: true
...